spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka1:9092,kafka2:9093,kafka3:9094}
