server:
  port: ${SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS}
    hostname: ${EUREKA_INSTANCE_HOSTNAME}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_JWK_URI}
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI}
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: ${USER_SERVICE_URI}
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URI}
          predicates:
            - Path=/api/notification/**
          filters:
            - StripPrefix=1

        - id: content-management-service
          uri: ${CONTENT_MANAGEMENT_SERVICE_URI}
          predicates:
            - Path=/api/content/**
          filters:
            - StripPrefix=1

        - id: product-service
          uri: ${PRODUCT_SERVICE_URI}
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /api/auth/v3/api-docs
        display-name: "Auth Service API"
      - name: User Service
        url: /api/user/v3/api-docs
        display-name: "User Service API"
      - name: Product Service
        url: /api/products/v3/api-docs
        display-name: "Product Service API"
      - name: Content Management Service
        url: /api/content/v3/api-docs
        display-name: "Content Management Service API"
      - name: Notification Service
        url: /api/notification/v3/api-docs
        display-name: "Notification Service API"
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs